languageCode: "en-us"
baseUrl: ""
title: "Vitali Plagov Blog"
theme: ["PaperMod"]
paginate: 10
disqusShortname: vplagov
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 0

params:
  env: production
  author: "Vitali Plagov"
  defaultTheme: auto
  DateFormat: "2006-01-02"
  ShowShareButtons: false
  disableSpecial1stPost: true
  description: ""

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
